media:
  - name: images
    label: Images
    input: public/images
    output: /public/images
content:
  - name: posts
    label: Posts
    type: collection
    path: src/posts
    view:
      fields: [ title, date, tags, body ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-mm-dd
          name:min: 2024-12-24
      - name: banner
        label: Banner Image
        type: image
      - name: bannerAlt
        label: Banner Alt Text
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
